--- 
title: "ENVS 567 - Advanced Project"
author: "Christian Ayala"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
description: |
  This is a book containing the code and explanations of the Advanced Project
  for the ENVS 567 class.
link-citations: yes
github-repo: Coayala/Adv_project_ENVS567
---

# Introduction

My advanced project involves performing a **differential abundance analysis** of *metabolomics* data using simple *custom functions* as well as **differential expression** analysis of gene count data using the widely used r package [`DESeq2`](https://bioconductor.org/packages/release/bioc/html/DESeq2.html) [@love2014moderated]. 

## Differential abundance analysis (DA) in *metabolomics*

Differential abundance analysis in *metabolomics* and *proteomics* involves identifying which metabolites/proteins (features) have significantly different abundances between two experimental groups.

## Differential expression analysis (DE) in *meta/transcriptomics*

Differential expression analysis for *meta/transcriptomics* involves taking the normalised read count data and performing statistical analysis to discover quantitative changes in expression levels between experimental groups.


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
